import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider afterSignInUrl="/" afterSignUpUrl="/onboarding">
      <html lang="ja">
        <body className={inter.className}>
          <a href={process.env.NEXT_PUBLIC_CLERK_USER_PROFILE as string} target="_blank">
            アカウント設定
          </a>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
